Sui bundler demo danielvillegas
trainings-juanmaguitar/schibsted-sui-tools-training-dec2018 pull request #6
Opened 2018-12-11 16:34 UTC by vior1992

2018-12-11 19:00 UTC, juanmaguitar requested changes
Fijate que has subido la carpeta `node_modules`

2018-12-11 19:23 UTC, vior1992 commented
Disculpa, se me ha colado la barra! Arreglado y borrado.

2018-12-11 19:24 UTC, juanmaguitar submitted a review, later dismissed

2018-12-13 13:56 UTC, juanmaguitar approved these changes

2018-12-13 13:56 UTC, merged

2018-12-13 13:57 UTC, nucliweb commented on staff/daniel-villegas/sui-bundler-demo/src/components/Form/index.js
> +      'user "' + name + '" with email "' + email + '" wrote: "' + text + '"'
`User ${name} with email ${email} wrote: ${text}`